server:
  port: 8003

spring:
  application:
    name: RECOMMENDED-SERVICE
  data:
    mongodb:
      database: recommendations
      port: 27017
      uri: mongodb://localhost:27017/recommendations
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka/